dataset:
  keypoints: "med_34"
  train: "./data/train.csv"
  val: "./data/val.csv"
  img_dir: "./data/cropped"
  sigma: 4.0
  preprocess:
    input_size: [576, 768]
    output_size: [144, 192]

model:
  name: "HRNet"
  weights: "weights/pose_hrnet_w48_384x288.pth"
  num_joints: 34
  W: 48

training:
  epochs: 10
  batch_size: 32
  optimizer: "adam"
  learning_rate: 0.01
  output_dir: "runs/"
