dataset:
  keypoints: "small_17"
  val: "./data/val.csv"
  train: "./data/train.csv"
  img_dir: "./data/cropped"
  sigma: 2.0
  preprocess:
    input_size: [640, 640]
    output_size: [48, 64]

model:
  name: "YOLO"
  variant: "yolov8x-pose"
  num_joints: 17
  scale_sizes: [80, 40, 20]

training:
  epochs: 5
  batch_size: 10
  optimizer: "adam"
  learning_rate: 0.001
  output_dir: "runs/"
