dataset:
  keypoints: "med_34"
  val: "./data/val.csv"
  train: "./data/train.csv"
  img_dir: "./data/cropped"
  sigma: 2.0
  preprocess:
    input_size: [192, 256]
    output_size: [48, 64]

model:
  name: "ViTPose"
  weights: "weights/vitpose-l-classic.pth"
  input_size: [192, 256]
  output_size: [48, 64]
  num_joints: 34
  variant: "L"
  decoder: "classic"

training:
  epochs: 5
  batch_size: 256
  optimizer: "adam"
  learning_rate: 0.001
  output_dir: "runs/"
