small_17: # same as COCO
  [
    "C7",
    "LFHD",
    "RFHD",
    "LBHD",
    "RBHD",
    "LSJC",
    "RSJC",
    "LEJC",
    "REJC",
    "LWJC",
    "RWJC",
    "LHJC",
    "RHJC",
    "LKJC",
    "RKJC",
    "LAJC",
    "RAJC",
  ]
med_34: # Include small + some more points
  [
    "C7",
    "LFHD",
    "RFHD",
    "LBHD",
    "RBHD",
    "LSJC",
    "RSJC",
    "LEJC",
    "REJC",
    "LWJC",
    "RWJC",
    "LHJC",
    "RHJC",
    "LKJC",
    "RKJC",
    "LAJC",
    "RAJC", # 17
    "CLAV",
    "STRN",
    "T10",
    "RHEE",
    "RTOE",
    "RFIN",
    "RWRB",
    "LASI",
    "RASI",
    "LPSI",
    "LHEE",
    "LELB",
    "RUPA",
    "LWRB",
    "RWRA",
    "LTHI",
    "RTHI",
  ]

all_63:
  [
    "C7",
    "CLAV",
    "CentreOfMass",
    "CentreOfMassFloor",
    "LAJC",
    "LANK",
    "LASI",
    "LBHD",
    "LEJC",
    "LELB",
    "LFHD",
    "LFIN",
    "LFRM",
    "LHEE",
    "LHJC",
    "LKJC",
    "LKNE",
    "LMMED",
    "LPSI",
    "LSHO",
    "LSJC",
    "LTHI",
    "LTIB",
    "LTOE",
    "LUPA",
    "LWJC",
    "LWRA",
    "LWRB",
    "L_Foot_Out",
    "MElbowL",
    "MElbowR",
    "MKNEL",
    "MKNER",
    "PelL",
    "PelR",
    "RAJC",
    "RANK",
    "RASI",
    "RBAK",
    "RBHD",
    "REJC",
    "RELB",
    "RFHD",
    "RFIN",
    "RFRM",
    "RHEE",
    "RHJC",
    "RKJC",
    "RKNE",
    "RMMED",
    "RPSI",
    "RSHO",
    "RSJC",
    "RTHI",
    "RTIB",
    "RTOE",
    "RUPA",
    "RWJC",
    "RWRA",
    "RWRB",
    "R_Foot_Out",
    "STRN",
    "T10",
  ]
